### ISSUE TITLE
部分文件或文件夹应该加入gitignore

### ISSUE THREAD

**Issue by 001eander** [drowsysomnolent/Stock-prediction-XGB-SHAP-streamlit#1]
像`__pycache__`这样的文件夹应该加入`.gitignore`文件中

`.gitignore`文件中应该有这样的内容
```text
__pycache__/
.ipynb_checkpoints/
```

为什么我不发起一个pull request？因为这是你们的大作业……

**Comment by lLiuRunze** [comment]
收到，上传的时候为了方便直接全上传了
pull吧，这么小个项目无所谓的

**Comment by 001eander** [comment]
oops，那我close了
